const cs = (title, summary, theory, task, expected, errors, question) => ({ title, summary, theory, task, expected, errors, question });
const sk = (title, summary, theory, task, expected, errors, question) => ({ title, summary, theory, task, expected, errors, question });
const command = (code, csDescription, skDescription, warning = false) => ({ code, description: { cs: csDescription, sk: skDescription }, warning });

export const chapters = [
  { id: "prepare", number: "00", name: { cs: "Příprava", sk: "Príprava" }, description: { cs: "Nástroje a kontrola počítače", sk: "Nástroje a kontrola počítača" } },
  { id: "local", number: "01", name: { cs: "Lokální Git", sk: "Lokálny Git" }, description: { cs: "Historie, větve a konflikty", sk: "História, vetvy a konflikty" } },
  { id: "github", number: "02", name: { cs: "GitHub", sk: "GitHub" }, description: { cs: "Sdílení a spolupráce", sk: "Zdieľanie a spolupráca" } },
  { id: "actions", number: "03", name: { cs: "GitHub Actions", sk: "GitHub Actions" }, description: { cs: "Automatické kontroly a nasazení", sk: "Automatické kontroly a nasadenie" } }
];

export const steps = [
  {
    id: "prepare-tools", chapter: "prepare", duration: 15,
    content: {
      cs: cs("Nástroje pro dílnu", "Připravíme Git Bash, Node.js a jeden bezpečný pracovní adresář.", ["Git je nástroj, který budeme ovládat příkazy. Na Windows je budeme psát do Git Bash. Node.js potřebujeme až pro spuštění ukázkového webu a testů."], ["Ověř, že příkazy níže vypíšou čísla verzí. Potom vytvoř pracovní adresář mimo OneDrive."], ["Každý příkaz vypíše verzi a příkaz pwd skončí cestou workshops/git-github."], ["Když příkaz není nalezen, zavři starý terminál a otevři nový Git Bash. Pokud nepomůže, vrať se k instalačnímu návodu."], "Proč po instalaci programu někdy nestačí staré okno terminálu?"),
      sk: sk("Nástroje pre dielňu", "Pripravíme Git Bash, Node.js a jeden bezpečný pracovný priečinok.", ["Git je nástroj, ktorý budeme ovládať príkazmi. Vo Windows ich budeme písať do Git Bash. Node.js potrebujeme až na spustenie ukážkového webu a testov."], ["Over, že príkazy nižšie vypíšu čísla verzií. Potom vytvor pracovný priečinok mimo OneDrive."], ["Každý príkaz vypíše verziu a príkaz pwd skončí cestou workshops/git-github."], ["Keď sa príkaz nenašiel, zavri starý terminál a otvor nový Git Bash. Ak to nepomôže, vráť sa k inštalačnému návodu."], "Prečo po inštalácii programu niekedy nestačí staré okno terminálu?")
    },
    commands: [command("git --version", "Ověří nainstalovaný Git.", "Overí nainštalovaný Git."), command("bash --version", "Ověří prostředí Git Bash.", "Overí prostredie Git Bash."), command("node --version && npm --version && npx --version", "Ověří Node.js a jeho nástroje.", "Overí Node.js a jeho nástroje."), command("mkdir -p ~/workshops/git-github\ncd ~/workshops/git-github\npwd", "Vytvoří pracovní adresář a vstoupí do něj.", "Vytvorí pracovný priečinok a vstúpi doň.")]
  },
  {
    id: "prepare-identity", chapter: "prepare", duration: 15,
    content: {
      cs: cs("Podepiš své commity", "Git musí vědět, kdo vytváří historii.", ["Jméno a e-mail se uloží do každého commitu. Nejde o přihlášení ani heslo. Použij e-mail ověřený na GitHubu nebo GitHub noreply adresu."], ["Nahraď ukázkové hodnoty svými údaji, nastav main jako výchozí větev a konfiguraci zkontroluj."], ["Výpis obsahuje tvoje jméno, správný e-mail a main."], ["Chyba Author identity unknown znamená, že některý údaj chybí. Staré commity se změnou konfigurace nepřepíšou."], "Jaký je rozdíl mezi identitou autora a přihlášením na GitHub?"),
      sk: sk("Podpíš svoje commity", "Git musí vedieť, kto vytvára históriu.", ["Meno a e-mail sa uložia do každého commitu. Nejde o prihlásenie ani heslo. Použi e-mail overený na GitHube alebo GitHub noreply adresu."], ["Nahraď ukážkové hodnoty svojimi údajmi, nastav main ako predvolenú vetvu a konfiguráciu skontroluj."], ["Výpis obsahuje tvoje meno, správny e-mail a main."], ["Chyba Author identity unknown znamená, že niektorý údaj chýba. Staré commity sa zmenou konfigurácie neprepíšu."], "Aký je rozdiel medzi identitou autora a prihlásením na GitHub?")
    },
    commands: [command('git config --global user.name "Jméno Příjmení"\ngit config --global user.email "email-z-githubu@example.com"\ngit config --global init.defaultBranch main', "Nastaví identitu a výchozí název větve.", "Nastaví identitu a predvolený názov vetvy."), command("git config --global user.name\ngit config --global user.email\ngit config --global init.defaultBranch", "Vypíše uložené hodnoty.", "Vypíše uložené hodnoty.")]
  },
  {
    id: "prepare-doctor", chapter: "prepare", duration: 15,
    content: {
      cs: cs("Kontrola před výpravou", "Sandbox sám ověří nejdůležitější části prostředí.", ["Klonování vytvoří místní kopii vzdáleného repozitáře. npm ci nainstaluje přesně zamčené závislosti a Playwright používá Chromium k ovládání webu."], ["Naklonuj sandbox, nainstaluj závislosti a spusť doctor i testy. Lektorovi pošli pouze závěrečný výstup doctoru."], ["Doctor skončí slovem READY a testy zeleným souhrnem."], ["Neposílej tokeny ani screenshot správce přihlašovacích údajů. Chromium lze zkusit stáhnout znovu příkazem npx playwright install chromium."], "Co nám ověřuje doctor a co už ověřují Playwright testy?"),
      sk: sk("Kontrola pred výpravou", "Sandbox sám overí najdôležitejšie časti prostredia.", ["Klonovanie vytvorí miestnu kópiu vzdialeného repozitára. npm ci nainštaluje presne zamknuté závislosti a Playwright používa Chromium na ovládanie webu."], ["Naklonuj sandbox, nainštaluj závislosti a spusti doctor aj testy. Lektorovi pošli iba záverečný výstup doctoru."], ["Doctor skončí slovom READY a testy zeleným súhrnom."], ["Neposielaj tokeny ani screenshot správcu prihlasovacích údajov. Chromium môžeš skúsiť stiahnuť znova príkazom npx playwright install chromium."], "Čo nám overuje doctor a čo už overujú Playwright testy?")
    },
    commands: [command("git clone https://github.com/Yrchdagnir/git-github-skoleni.git\ncd git-github-skoleni", "Stáhne sandbox a vstoupí do něj.", "Stiahne sandbox a vstúpi doň."), command("npm ci\nnpx playwright install chromium\nnpm run doctor\nnpm test", "Připraví projekt a spustí kontroly.", "Pripraví projekt a spustí kontroly.")]
  },
  {
    id: "local-repository", chapter: "local", duration: 20,
    content: {
      cs: cs("Založ vlastní dílnu", "Repozitář je obyčejná složka, ve které Git sleduje historii.", ["Příkaz git init vytvoří skrytou složku .git. Ta obsahuje historii a ukazatele větví; tvoje pracovní soubory zůstávají vedle ní. HEAD říká, na které větvi právě stojíš."], ["V pracovním adresáři vytvoř moje-alchymisticka-dilna, inicializuj Git a pomocí Notepadu vytvoř dilna.txt s názvem a účelem dílny."], ["git status ukáže větev main, zatím žádné commity a nový nesledovaný soubor dilna.txt."], ["Příkaz nespouštěj znovu v nadřazeném adresáři. Pomocí pwd a git status vždy ověř, kde právě jsi."], "Co je uložené v .git a co je working tree?"),
      sk: sk("Založ vlastnú dielňu", "Repozitár je obyčajný priečinok, v ktorom Git sleduje históriu.", ["Príkaz git init vytvorí skrytý priečinok .git. Ten obsahuje históriu a ukazovatele vetiev; tvoje pracovné súbory zostávajú vedľa neho. HEAD hovorí, na ktorej vetve práve stojíš."], ["V pracovnom priečinku vytvor moje-alchymisticka-dilna, inicializuj Git a pomocou Notepadu vytvor dilna.txt s názvom a účelom dielne."], ["git status ukáže vetvu main, zatiaľ žiadne commity a nový nesledovaný súbor dilna.txt."], ["Príkaz nespúšťaj znova v nadradenom priečinku. Pomocou pwd a git status vždy over, kde práve si."], "Čo je uložené v .git a čo je working tree?")
    },
    commands: [command("cd ~/workshops/git-github\nmkdir moje-alchymisticka-dilna\ncd moje-alchymisticka-dilna\ngit init", "Vytvoří a inicializuje lokální repo.", "Vytvorí a inicializuje lokálny repozitár."), command("notepad dilna.txt\ngit status", "Otevře textový soubor a ukáže stav repa.", "Otvorí textový súbor a ukáže stav repozitára.")]
  },
  {
    id: "local-staging", chapter: "local", duration: 25,
    content: {
      cs: cs("Od změny ke commitu", "Staging area je přípravný tác: vybíráš na něj přesně to, co patří do dalšího záznamu historie.", ["Working tree jsou soubory, které právě upravuješ. Staging area je výběr pro příští commit. Commit je uložený snímek s autorem, časem, zprávou a vazbou na předchozí snímek."], ["Přidej dilna.txt do staging area, prohlédni rozdíl a vytvoř první commit. Potom vytvoř lektvary.txt a samostatný druhý commit."], ["Historie obsahuje dva logicky oddělené commity a git status hlásí čistý pracovní strom."], ["git diff ukazuje změny mimo staging. Pro připravené změny použij git diff --staged. Před commitem se vždy podívej na git status."], "Proč není staging area totéž co commit?"),
      sk: sk("Od zmeny ku commitu", "Staging area je prípravný podnos: vyberáš naň presne to, čo patrí do ďalšieho záznamu histórie.", ["Working tree sú súbory, ktoré práve upravuješ. Staging area je výber pre budúci commit. Commit je uložená snímka s autorom, časom, správou a väzbou na predchádzajúcu snímku."], ["Pridaj dilna.txt do staging area, prezri rozdiel a vytvor prvý commit. Potom vytvor lektvary.txt a samostatný druhý commit."], ["História obsahuje dva logicky oddelené commity a git status hlási čistý pracovný strom."], ["git diff ukazuje zmeny mimo staging. Pre pripravené zmeny použi git diff --staged. Pred commitom sa vždy pozri na git status."], "Prečo nie je staging area to isté ako commit?")
    },
    commands: [command("git add dilna.txt\ngit diff --staged\ngit commit -m \"docs: popsat alchymistickou dilnu\"", "Vybere soubor a uloží první commit.", "Vyberie súbor a uloží prvý commit."), command("notepad lektvary.txt\ngit add lektvary.txt\ngit commit -m \"feat: pridat seznam lektvaru\"\ngit status", "Vytvoří druhý samostatný commit.", "Vytvorí druhý samostatný commit.")]
  },
  {
    id: "local-history", chapter: "local", duration: 20,
    content: {
      cs: cs("Čti historii", "Git není jen tlačítko Uložit. Umí ukázat, kdo, kdy a proč změnu udělal.", ["Každý commit má jedinečný hash. HEAD obvykle ukazuje na poslední commit aktuální větve. log ukazuje cestu historií, show obsah jednoho commitu a blame původ jednotlivých řádků."], ["Najdi hash posledního commitu, prohlédni jeho obsah a zjisti autora prvního řádku v dilna.txt."], ["Dokážeš ukázat poslední commit, jeho změnu a autora konkrétního řádku."], ["Hash nemusíš opisovat celý; obvykle stačí jeho první jednoznačné znaky. blame neurčuje vinu, pouze původ řádku."], "Na co ukazuje HEAD a proč se po commitu posune?"),
      sk: sk("Čítaj históriu", "Git nie je iba tlačidlo Uložiť. Vie ukázať, kto, kedy a prečo zmenu urobil.", ["Každý commit má jedinečný hash. HEAD zvyčajne ukazuje na posledný commit aktuálnej vetvy. log ukazuje cestu históriou, show obsah jedného commitu a blame pôvod jednotlivých riadkov."], ["Nájdi hash posledného commitu, prezri jeho obsah a zisti autora prvého riadku v dilna.txt."], ["Dokážeš ukázať posledný commit, jeho zmenu a autora konkrétneho riadku."], ["Hash nemusíš opisovať celý; zvyčajne stačia jeho prvé jednoznačné znaky. blame neurčuje vinu, iba pôvod riadku."], "Na čo ukazuje HEAD a prečo sa po commite posunie?")
    },
    commands: [command("git log --oneline --graph --decorate --all", "Ukáže přehledný graf celé historie.", "Ukáže prehľadný graf celej histórie."), command("git show HEAD", "Ukáže poslední commit včetně změny.", "Ukáže posledný commit vrátane zmeny."), command("git blame dilna.txt", "Ukáže původ řádků souboru.", "Ukáže pôvod riadkov súboru.")]
  },
  {
    id: "local-undo", chapter: "local", duration: 25,
    content: {
      cs: cs("Vracej změny vědomě", "Jiný příkaz se hodí před commitem, jiný po něm a jiný ve sdílené historii.", ["restore vrací obsah souboru nebo ho vyjme ze staging area. amend nahradí poslední lokální commit. revert vytvoří nový opačný commit a zachová záznam toho, co se stalo. reset posouvá ukazatel historie a vyžaduje opatrnost."], ["Vyzkoušej zahodit necommitnutou změnu, vyjmout soubor ze staging area a doplnit poslední lokální commit pomocí amend. Revert použij na cvičném commitu."], ["Po každém pokusu dokážeš z git status a log vysvětlit, co se změnilo v souborech a co v historii."], ["reset --hard může zahodit práci. V tomto školení patří jen do zahoditelného lokálního repa; na sdílenou změnu použij revert."], "Proč je revert vhodnější pro commit, který už viděli ostatní?"),
      sk: sk("Vracaj zmeny vedome", "Iný príkaz sa hodí pred commitom, iný po ňom a iný v zdieľanej histórii.", ["restore vracia obsah súboru alebo ho vyberie zo staging area. amend nahradí posledný lokálny commit. revert vytvorí nový opačný commit a zachová záznam toho, čo sa stalo. reset posúva ukazovateľ histórie a vyžaduje opatrnosť."], ["Vyskúšaj zahodiť necommitnutú zmenu, vybrať súbor zo staging area a doplniť posledný lokálny commit pomocou amend. Revert použi na cvičnom commite."], ["Po každom pokuse dokážeš z git status a log vysvetliť, čo sa zmenilo v súboroch a čo v histórii."], ["reset --hard môže zahodiť prácu. V tomto školení patrí iba do zahoditeľného lokálneho repozitára; na zdieľanú zmenu použi revert."], "Prečo je revert vhodnejší pre commit, ktorý už videli ostatní?")
    },
    commands: [command("git restore dilna.txt", "Zahodí necommitnuté změny souboru.", "Zahodí necommitnuté zmeny súboru."), command("git restore --staged lektvary.txt", "Vyjme soubor ze staging area, obsah zachová.", "Vyberie súbor zo staging area, obsah zachová."), command("git commit --amend --no-edit", "Nahradí poslední lokální commit novou verzí.", "Nahradí posledný lokálny commit novou verziou."), command("git revert HASH", "Přidá commit s opačnou změnou.", "Pridá commit s opačnou zmenou."), command("git reset --hard HEAD~1", "Posune lokální historii a zahodí změny.", "Posunie lokálnu históriu a zahodí zmeny.", true)]
  },
  {
    id: "local-branches", chapter: "local", duration: 25,
    content: {
      cs: cs("Pracuj ve větvi", "Větev je pohyblivý ukazatel na řadu commitů, ne druhá kopie celé složky.", ["Nová větev začíná na současném commitu. switch přepíná, kam ukazuje HEAD. Merge spojí práci větve do aktuální větve; někdy jen posune ukazatel, jindy vytvoří merge commit."], ["Vytvoř větev feature/uspavaci-elixir, doplň recept do lektvary.txt a commitni. Na main přidej rovnovaha.txt a commitni. Potom slouč feature větev do main."], ["Graf historie ukazuje dvě linie spojené merge commitem a main obsahuje oba soubory."], ["Před přepnutím větve zkontroluj git status. Necommitnuté změny mohou přepnutí zablokovat nebo se přenést s tebou."], "Co přesně vytváří větev a kam při přepnutí ukazuje HEAD?"),
      sk: sk("Pracuj vo vetve", "Vetva je pohyblivý ukazovateľ na rad commitov, nie druhá kópia celého priečinka.", ["Nová vetva začína na súčasnom commite. switch prepína, kam ukazuje HEAD. Merge spojí prácu vetvy do aktuálnej vetvy; niekedy iba posunie ukazovateľ, inokedy vytvorí merge commit."], ["Vytvor vetvu feature/uspavaci-elixir, doplň recept do lektvary.txt a commitni. Na main pridaj rovnovaha.txt a commitni. Potom zlúč feature vetvu do main."], ["Graf histórie ukazuje dve línie spojené merge commitom a main obsahuje oba súbory."], ["Pred prepnutím vetvy skontroluj git status. Necommitnuté zmeny môžu prepnutie zablokovať alebo sa preniesť s tebou."], "Čo presne vytvára vetva a kam pri prepnutí ukazuje HEAD?")
    },
    commands: [command("git switch -c feature/uspavaci-elixir", "Vytvoří větev a přepne se na ni.", "Vytvorí vetvu a prepne sa na ňu."), command("git switch main\ngit merge --no-ff feature/uspavaci-elixir", "Vrátí se na main a vytvoří merge commit.", "Vráti sa na main a vytvorí merge commit."), command("git log --oneline --graph --decorate --all", "Ukáže spojené linie historie.", "Ukáže spojené línie histórie.")]
  },
  {
    id: "local-conflict", chapter: "local", duration: 25,
    content: {
      cs: cs("Vyřeš konflikt", "Konflikt není porucha. Git pouze potřebuje člověka, aby rozhodl mezi dvěma změnami stejného místa.", ["Konfliktní značky oddělují verzi aktuální větve a připojované větve. Výsledek může být jedna z nich nebo úplně nová dohoda. Git pozná rozhodnutí až po git add."], ["Na main a nové větvi změň stejný řádek Obtížnost v rovnovaha.txt na dvě různé hodnoty. Spusť merge, otevři soubor, dohodni konečný obsah, odstraň značky a merge dokonči."], ["V souboru nejsou konfliktní značky, git status je čistý a historie obsahuje dokončený merge."], ["Nemaž celý soubor ani složku .git. Chceš-li pokus zrušit a začít znovu, použij git merge --abort."], "Jak Git pozná, že jsi konflikt opravdu vyřešil?"),
      sk: sk("Vyrieš konflikt", "Konflikt nie je porucha. Git iba potrebuje človeka, aby rozhodol medzi dvoma zmenami rovnakého miesta.", ["Konfliktné značky oddeľujú verziu aktuálnej vetvy a pripájanej vetvy. Výsledok môže byť jedna z nich alebo úplne nová dohoda. Git spozná rozhodnutie až po git add."], ["Na main a novej vetve zmeň rovnaký riadok Náročnosť v rovnovaha.txt na dve rôzne hodnoty. Spusti merge, otvor súbor, dohodni konečný obsah, odstráň značky a merge dokonči."], ["V súbore nie sú konfliktné značky, git status je čistý a história obsahuje dokončený merge."], ["Nemaž celý súbor ani priečinok .git. Ak chceš pokus zrušiť a začať znova, použi git merge --abort."], "Ako Git spozná, že si konflikt naozaj vyriešil?")
    },
    commands: [command("git status\nnotepad rovnovaha.txt", "Ukáže konfliktní soubor a otevře ho.", "Ukáže konfliktný súbor a otvorí ho."), command("git add rovnovaha.txt\ngit commit", "Označí obsah za vyřešený a dokončí merge.", "Označí obsah za vyriešený a dokončí merge."), command("git merge --abort", "Zruší celý probíhající merge.", "Zruší celé prebiehajúce zlúčenie.")]
  },
  {
    id: "local-tag", chapter: "local", duration: 10,
    content: {
      cs: cs("Označ první verzi", "Tag je stabilní jmenovka konkrétního commitu.", ["Větev se s novými commity pohybuje. Anotovaný tag obvykle zůstane na místě a nese název, zprávu i autora označení."], ["Označ současný stav dílny tagem v0.1.0 a zobraz jeho detail."], ["git show v0.1.0 ukáže anotaci i označený commit."], ["Tag se na vzdálený repozitář neposílá automaticky s běžným push; později ho pošleme zvlášť."], "Jak se chová tag jinak než větev?"),
      sk: sk("Označ prvú verziu", "Tag je stabilná menovka konkrétneho commitu.", ["Vetva sa s novými commitmi pohybuje. Anotovaný tag zvyčajne zostane na mieste a nesie názov, správu aj autora označenia."], ["Označ súčasný stav dielne tagom v0.1.0 a zobraz jeho detail."], ["git show v0.1.0 ukáže anotáciu aj označený commit."], ["Tag sa do vzdialeného repozitára neposiela automaticky s bežným push; neskôr ho pošleme osobitne."], "Ako sa správa tag inak než vetva?")
    },
    commands: [command('git tag -a v0.1.0 -m "Prvni verze alchymisticke dilny"', "Vytvoří anotovaný tag.", "Vytvorí anotovaný tag."), command("git tag\ngit show v0.1.0", "Vypíše tagy a detail verze.", "Vypíše tagy a detail verzie.")]
  },
  {
    id: "github-remote", chapter: "github", duration: 25,
    content: {
      cs: cs("Git potkává GitHub", "Git spravuje historii. GitHub ji hostuje a přidává spolupráci.", ["Remote je pojmenované spojení na jiný repozitář. Běžný název origin není kouzelné slovo, jen zavedená přezdívka. Push posílá lokální commity a -u nastaví sledovanou vzdálenou větev."], ["Na GitHubu vytvoř prázdné repo moje-alchymisticka-dilna, přidej jeho HTTPS adresu jako origin a publikuj main i tag."], ["git remote -v ukazuje adresu, main sleduje origin/main a tag v0.1.0 je vidět na GitHubu."], ["Nevkládej token do URL. Přihlášení přes HTTPS bezpečně zprostředkuje Git Credential Manager."], "Co je origin a co se nastaví přepínačem -u?"),
      sk: sk("Git stretáva GitHub", "Git spravuje históriu. GitHub ju hostuje a pridáva spoluprácu.", ["Remote je pomenované spojenie na iný repozitár. Bežný názov origin nie je čarovné slovo, iba zaužívaná prezývka. Push posiela lokálne commity a -u nastaví sledovanú vzdialenú vetvu."], ["Na GitHube vytvor prázdny repozitár moje-alchymisticka-dilna, pridaj jeho HTTPS adresu ako origin a publikuj main aj tag."], ["git remote -v ukazuje adresu, main sleduje origin/main a tag v0.1.0 je viditeľný na GitHube."], ["Nevkladaj token do URL. Prihlásenie cez HTTPS bezpečne sprostredkuje Git Credential Manager."], "Čo je origin a čo sa nastaví prepínačom -u?")
    },
    commands: [command("git remote add origin https://github.com/GITHUB_USER/moje-alchymisticka-dilna.git", "Pojmenuje vzdálené repo origin.", "Pomenuje vzdialený repozitár origin."), command("git push -u origin main\ngit push origin v0.1.0", "Publikuje větev, nastaví upstream a pošle tag.", "Publikuje vetvu, nastaví upstream a pošle tag."), command("git remote -v\ngit status", "Ověří remote a sledovanou větev.", "Overí remote a sledovanú vetvu.")]
  },
  {
    id: "github-sync", chapter: "github", duration: 25,
    content: {
      cs: cs("Rozliš clone, fetch a pull", "Každá lokální kopie má vlastní pracovní soubory i vlastní historii.", ["clone vytvoří novou kopii a nastaví origin. fetch stáhne nové informace do remote-tracking větví jako origin/main, ale nemění tvoje soubory. pull obvykle provede fetch a potom začlení změny do aktuální větve."], ["Naklonuj svou dílnu do druhého adresáře. V první kopii pushni nový commit. Ve druhé nejdřív použij fetch, porovnej main s origin/main a až potom pull."], ["Po fetch zůstanou soubory beze změny, ale graf ukáže nový origin/main. Po pull se lokální main i soubory aktualizují."], ["Když je push odmítnut jako non-fast-forward, nepoužívej automaticky force. Nejdřív fetch, status a graf historie."], "Jaký viditelný rozdíl je mezi fetch a pull?"),
      sk: sk("Rozliš clone, fetch a pull", "Každá lokálna kópia má vlastné pracovné súbory aj vlastnú históriu.", ["clone vytvorí novú kópiu a nastaví origin. fetch stiahne nové informácie do remote-tracking vetiev ako origin/main, ale nemení tvoje súbory. pull zvyčajne vykoná fetch a potom začlení zmeny do aktuálnej vetvy."], ["Naklonuj svoju dielňu do druhého priečinka. V prvej kópii pushni nový commit. V druhej najprv použi fetch, porovnaj main s origin/main a až potom pull."], ["Po fetch zostanú súbory bez zmeny, ale graf ukáže nový origin/main. Po pull sa lokálny main aj súbory aktualizujú."], ["Keď je push odmietnutý ako non-fast-forward, nepoužívaj automaticky force. Najprv fetch, status a graf histórie."], "Aký viditeľný rozdiel je medzi fetch a pull?")
    },
    commands: [command("git clone https://github.com/GITHUB_USER/moje-alchymisticka-dilna.git druha-dilna", "Vytvoří druhou lokální kopii.", "Vytvorí druhú lokálnu kópiu."), command("git fetch origin\ngit log --oneline --graph --decorate --all", "Stáhne historii bez změny pracovních souborů.", "Stiahne históriu bez zmeny pracovných súborov."), command("git diff main..origin/main\ngit pull", "Porovná a potom začlení vzdálenou změnu.", "Porovná a potom začlení vzdialenú zmenu.")]
  },
  {
    id: "github-recipe", chapter: "github", duration: 30,
    content: {
      cs: cs("Přidej vlastní lektvar", "Ve sdíleném sandboxu pracuje každý ve vlastní větvi.", ["Recept je JSON soubor: vlevo jsou názvy polí, vpravo jejich hodnoty. locale musí být cs nebo sk, slug používá malá písmena, číslice a pomlčky. Všechna textová pole a seznam ingrediencí musí být vyplněné."], ["V sandboxu vytvoř participant/GITHUB_USER/potion-recipe, zkopíruj šablonu a doplň vlastní recept. Pro druhý jazyk můžeš přidat druhý soubor se stejným slug. Obrázek je volitelný."], ["npm run build přijme data, npm test zůstane zelený a nová karta je vidět jen v jazyce uvedeném v locale."], ["Neměň názvy polí ani nemaž čárky a uvozovky. Recept pouze v češtině se ve slovenštině nezobrazí."], "Proč mají jazykové varianty stejný slug, ale jiné locale?"),
      sk: sk("Pridaj vlastný elixír", "V zdieľanom sandboxe pracuje každý vo vlastnej vetve.", ["Recept je JSON súbor: vľavo sú názvy polí, vpravo ich hodnoty. locale musí byť cs alebo sk, slug používa malé písmená, číslice a pomlčky. Všetky textové polia a zoznam ingrediencií musia byť vyplnené."], ["V sandboxe vytvor participant/GITHUB_USER/potion-recipe, skopíruj šablónu a doplň vlastný recept. Pre druhý jazyk môžeš pridať druhý súbor s rovnakým slug. Obrázok je voliteľný."], ["npm run build prijme dáta, npm test zostane zelený a nová karta je viditeľná iba v jazyku uvedenom v locale."], ["Nemeň názvy polí ani nemaž čiarky a úvodzovky. Recept iba v slovenčine sa v češtine nezobrazí."], "Prečo majú jazykové varianty rovnaký slug, ale iné locale?")
    },
    commands: [command("git switch -c participant/GITHUB_USER/potion-recipe", "Vytvoří osobní pracovní větev.", "Vytvorí osobnú pracovnú vetvu."), command("cp recipes/_template.json recipes/GITHUB_USER-muj-lektvar.json\nnotepad recipes/GITHUB_USER-muj-lektvar.json", "Zkopíruje a otevře šablonu receptu.", "Skopíruje a otvorí šablónu receptu."), command("npm run build\nnpm test", "Ověří data a chování webu.", "Overí dáta a správanie webu."), command("git add recipes/GITHUB_USER-muj-lektvar.json\ngit commit -m \"feat: pridat recept lektvaru\"\ngit push -u origin participant/GITHUB_USER/potion-recipe", "Uloží a publikuje změnu.", "Uloží a publikuje zmenu.")]
  },
  {
    id: "github-pr", chapter: "github", duration: 25,
    content: {
      cs: cs("Otevři pull request", "Pull request je žádost o společné posouzení a sloučení větve.", ["PR ukazuje rozdíl proti cílové větvi, automatické kontroly a diskusi. GitHub label třídí PR nebo issue; Git tag označuje konkrétní commit v historii. Jsou to odlišné věci."], ["Otevři PR do main s názvem feat: add potion recipe. Popiš co, proč a jak jsi změnu ověřil. Přidej label exercise a požádej partnera o review."], ["PR má čitelný diff, zelené kontroly, label a přiřazeného reviewera."], ["Název PR kontroluje workflow. Commitům dávej Conventional Commit zprávy také, protože release čte skutečnou historii po merge."], "Jaký problém řeší PR a jaký GitHub label?"),
      sk: sk("Otvor pull request", "Pull request je žiadosť o spoločné posúdenie a zlúčenie vetvy.", ["PR ukazuje rozdiel oproti cieľovej vetve, automatické kontroly a diskusiu. GitHub label triedi PR alebo issue; Git tag označuje konkrétny commit v histórii. Sú to odlišné veci."], ["Otvor PR do main s názvom feat: add potion recipe. Popíš čo, prečo a ako si zmenu overil. Pridaj label exercise a požiadaj partnera o review."], ["PR má čitateľný diff, zelené kontroly, label a priradeného reviewera."], ["Názov PR kontroluje workflow. Commitom dávaj Conventional Commit správy tiež, pretože release číta skutočnú históriu po merge."], "Aký problém rieši PR a aký GitHub label?")
    },
    commands: []
  },
  {
    id: "github-review", chapter: "github", duration: 20,
    content: {
      cs: cs("Review je rozhovor o změně", "Dobré review kontroluje konkrétní výsledek a pomáhá autorovi rozhodnout.", ["Komentář může být otázka, návrh nebo požadovaná oprava. Autor odpoví, přidá další commit do stejné větve a PR se automaticky aktualizuje. O schválení rozhoduje reviewer až nad aktuálním stavem."], ["Zkontroluj partnerův recept, spusť testy nebo ověř povinná pole a napiš jednu konkrétní připomínku. Autor ji opraví novým Conventional Commitem a pushne do stejné větve."], ["Diskuse je vyřešená, nové kontroly jsou zelené a PR má schválení."], ["Samotné Looks good nevysvětluje, co bylo ověřeno. Neopravuj cizí větev bez dohody."], "Co se stane s PR, když autor pushne další commit do stejné větve?"),
      sk: sk("Review je rozhovor o zmene", "Dobré review kontroluje konkrétny výsledok a pomáha autorovi rozhodnúť.", ["Komentár môže byť otázka, návrh alebo požadovaná oprava. Autor odpovie, pridá ďalší commit do rovnakej vetvy a PR sa automaticky aktualizuje. O schválení rozhoduje reviewer až nad aktuálnym stavom."], ["Skontroluj partnerov recept, spusti testy alebo over povinné polia a napíš jednu konkrétnu pripomienku. Autor ju opraví novým Conventional Commitom a pushne do rovnakej vetvy."], ["Diskusia je vyriešená, nové kontroly sú zelené a PR má schválenie."], ["Samotné Looks good nevysvetľuje, čo bolo overené. Neopravuj cudziu vetvu bez dohody."], "Čo sa stane s PR, keď autor pushne ďalší commit do rovnakej vetvy?")
    },
    commands: [command("git add recipes/GITHUB_USER-muj-lektvar.json\ngit commit -m \"fix: zapracovat pripominku z review\"\ngit push", "Přidá opravu do stejného PR.", "Pridá opravu do rovnakého PR.")]
  },
  {
    id: "github-conflict", chapter: "github", duration: 25,
    content: {
      cs: cs("Sluč změny partnera", "Konflikt může vzniknout i mezi dvěma PR; řešení ale pořád probíhá v Gitu.", ["Po merge prvního PR se origin/main posune. Druhá větev jej načte přes fetch a sloučí přes merge. Tím se konflikt objeví lokálně a řešení lze před pushem otestovat."], ["Ve dvojici upravte stejný řádek data/shared-recipe.txt. Po merge prvního PR druhý účastník sloučí origin/main, dohodne výslednou ingredienci, dokončí merge commit a pushne."], ["Druhý PR už nemá konflikt, obsahuje merge commit a testy jsou zelené."], ["Nepoužívej force push. Před řešením ověř aktuální větev a stáhni novou vzdálenou historii pomocí fetch."], "Proč slučujeme origin/main do pracovní větve, a ne naopak?"),
      sk: sk("Zlúč zmeny partnera", "Konflikt môže vzniknúť aj medzi dvoma PR; riešenie však stále prebieha v Gite.", ["Po merge prvého PR sa origin/main posunie. Druhá vetva ho načíta cez fetch a zlúči cez merge. Tým sa konflikt objaví lokálne a riešenie možno pred pushom otestovať."], ["Vo dvojici upravte rovnaký riadok data/shared-recipe.txt. Po merge prvého PR druhý účastník zlúči origin/main, dohodne výslednú ingredienciu, dokončí merge commit a pushne."], ["Druhý PR už nemá konflikt, obsahuje merge commit a testy sú zelené."], ["Nepoužívaj force push. Pred riešením over aktuálnu vetvu a stiahni novú vzdialenú históriu pomocou fetch."], "Prečo zlučujeme origin/main do pracovnej vetvy, a nie naopak?")
    },
    commands: [command("git fetch origin\ngit merge origin/main", "Stáhne a sloučí aktuální main do pracovní větve.", "Stiahne a zlúči aktuálny main do pracovnej vetvy."), command("git status\nnotepad data/shared-recipe.txt", "Ukáže a otevře konflikt.", "Ukáže a otvorí konflikt."), command("git add data/shared-recipe.txt\ngit commit -m \"merge: vyresit sdilenou ingredienci\"\nnpm test\ngit push", "Dokončí, otestuje a publikuje řešení.", "Dokončí, otestuje a publikuje riešenie.")]
  },
  {
    id: "github-cleanup", chapter: "github", duration: 10,
    content: {
      cs: cs("Merge commit a úklid", "Po schválení použijeme Create a merge commit a pracovní větev smažeme.", ["Merge commit zachová jednotlivé pracovní commity i viditelné místo spojení. Smazání větve po merge nemaže začleněnou historii; odstraňuje jen už nepotřebný ukazatel."], ["Po zelených kontrolách a schválení zvol Create a merge commit. Ověř automatické smazání větve na GitHubu, lokálně aktualizuj main a odstraň místní větev."], ["main obsahuje změnu i merge commit a seznam větví už neobsahuje dokončenou pracovní větev."], ["Větev maž až po úspěšném merge. git branch -d odmítne smazat větev, kterou Git nepovažuje za sloučenou."], "Proč smazání sloučené větve nesmaže její commity?"),
      sk: sk("Merge commit a upratovanie", "Po schválení použijeme Create a merge commit a pracovnú vetvu zmažeme.", ["Merge commit zachová jednotlivé pracovné commity aj viditeľné miesto spojenia. Zmazanie vetvy po merge nemaže začlenenú históriu; odstráni iba nepotrebný ukazovateľ."], ["Po zelených kontrolách a schválení zvoľ Create a merge commit. Over automatické zmazanie vetvy na GitHube, lokálne aktualizuj main a odstráň miestnu vetvu."], ["main obsahuje zmenu aj merge commit a zoznam vetiev už neobsahuje dokončenú pracovnú vetvu."], ["Vetvu maž až po úspešnom merge. git branch -d odmietne zmazať vetvu, ktorú Git nepovažuje za zlúčenú."], "Prečo zmazanie zlúčenej vetvy nezmaže jej commity?")
    },
    commands: [command("git switch main\ngit pull\ngit branch -d participant/GITHUB_USER/potion-recipe\ngit fetch --prune", "Aktualizuje main a odstraní staré ukazatele.", "Aktualizuje main a odstráni staré ukazovatele.")]
  },
  {
    id: "actions-model", chapter: "actions", duration: 25,
    content: {
      cs: cs("Co je GitHub Actions", "Workflow je automatický postup spuštěný konkrétní událostí.", ["Event je spouštěč, například pull_request. Workflow je YAML soubor. Job běží na čerstvém runneru a skládá se ze steps. Nenulový exit code označí krok i job jako neúspěšný."], ["Otevři .github/workflows/ci.yml a najdi eventy, runner, kroky, příkaz testu, oprávnění a podmínku uploadu artifactu."], ["Dokážeš vlastními slovy projít cestu od otevření PR po zelený nebo červený check."], ["YAML je citlivý na odsazení. Vztahy určují mezery, ne složené závorky."], "Která část workflow rozhoduje, kdy se automatizace spustí?"),
      sk: sk("Čo je GitHub Actions", "Workflow je automatický postup spustený konkrétnou udalosťou.", ["Event je spúšťač, napríklad pull_request. Workflow je YAML súbor. Job beží na čerstvom runneri a skladá sa zo steps. Nenulový exit code označí krok aj job ako neúspešný."], ["Otvor .github/workflows/ci.yml a nájdi eventy, runner, kroky, príkaz testu, oprávnenia a podmienku uploadu artifactu."], ["Dokážeš vlastnými slovami prejsť cestu od otvorenia PR po zelený alebo červený check."], ["YAML je citlivý na odsadenie. Vzťahy určujú medzery, nie zložené zátvorky."], "Ktorá časť workflow rozhoduje, kedy sa automatizácia spustí?")
    }, commands: [command("notepad .github/workflows/ci.yml", "Otevře CI workflow jako obyčejný text.", "Otvorí CI workflow ako obyčajný text.")]
  },
  {
    id: "actions-local-tests", chapter: "actions", duration: 20,
    content: {
      cs: cs("Testuj před pushem", "Automatická kontrola v cloudu používá stejné projektové příkazy jako ty lokálně.", ["Build přečte a ověří JSON recepty. Playwright otevře web v Chromiu a kontroluje chování, které vidí uživatel: recepty, jazyk a průvodce. CI přidává čisté prostředí, opakovatelnost a společný výsledek."], ["Spusť build, lokální web a testy. V samostatném okně otevři adresu serveru a porovnej ji s výstupem testů."], ["Build vygeneruje data a Playwright testy skončí zeleně. Lokální web běží na uvedené adrese."], ["Běžící server ukončíš Ctrl+C. Pokud port používá jiný proces, nejdřív zavři předchozí server."], "Proč má smysl spouštět stejné testy lokálně i v CI?"),
      sk: sk("Testuj pred pushom", "Automatická kontrola v cloude používa rovnaké projektové príkazy ako ty lokálne.", ["Build prečíta a overí JSON recepty. Playwright otvorí web v Chromiu a kontroluje správanie, ktoré vidí používateľ: recepty, jazyk a sprievodcu. CI pridáva čisté prostredie, opakovateľnosť a spoločný výsledok."], ["Spusti build, lokálny web a testy. V samostatnom okne otvor adresu servera a porovnaj ju s výstupom testov."], ["Build vygeneruje dáta a Playwright testy skončia zeleno. Lokálny web beží na uvedenej adrese."], ["Bežiaci server ukončíš Ctrl+C. Ak port používa iný proces, najprv zavri predchádzajúci server."], "Prečo má zmysel spúšťať rovnaké testy lokálne aj v CI?")
    }, commands: [command("npm run build\nnpm test", "Sestaví data a spustí celý testovací balík.", "Zostaví dáta a spustí celý testovací balík."), command("npm run dev", "Spustí lokální webový server.", "Spustí lokálny webový server.")]
  },
  {
    id: "actions-edit-workflow", chapter: "actions", duration: 25,
    content: {
      cs: cs("Sestav vlastní PR workflow", "Z připravené šablony vytvoříš Action, která reaguje jen na pull requesty do main a vypíše tvoji zprávu.", ["Klíč on určuje událost, která workflow spustí. Událost pull_request lze omezit filtrem branches na cílovou větev. Job obsahuje kroky a run pošle příkaz do shellu runneru."], ["Ve vlastní větvi zkopíruj workshop/templates/pr-message.yml jako .github/workflows/pr-message-GITHUB_USER.yml. Nahraď WORKSHOP_EVENT událostí pro pull request, WORKSHOP_BRANCH cílovou větví main a WORKSHOP_MESSAGE vlastní zprávou. Všechny tři zástupné hodnoty musí zmizet. Commitni, pushni a otevři PR."], ["Po otevření PR se objeví workflow PR message exercise. Job Print PR message proběhne zeleně a krok Print message vypíše tvoji zprávu."], ["Šablonu neupravuj na původním místě. Aktivní workflow musí být v .github/workflows a YAML musí zachovat správné odsazení. npm test odmítne ponechané zástupné hodnoty."], "Proč filtr branches u události pull_request sleduje cílovou větev PR?"),
      sk: sk("Zostav vlastné PR workflow", "Z pripravenej šablóny vytvoríš Action, ktorá reaguje iba na pull requesty do main a vypíše tvoju správu.", ["Kľúč on určuje udalosť, ktorá workflow spustí. Udalosť pull_request možno obmedziť filtrom branches na cieľovú vetvu. Job obsahuje kroky a run odošle príkaz do shellu runnera."], ["Vo vlastnej vetve skopíruj workshop/templates/pr-message.yml ako .github/workflows/pr-message-GITHUB_USER.yml. Nahraď WORKSHOP_EVENT udalosťou pre pull request, WORKSHOP_BRANCH cieľovou vetvou main a WORKSHOP_MESSAGE vlastnou správou. Všetky tri zástupné hodnoty musia zmiznúť. Commitni, pushni a otvor PR."], ["Po otvorení PR sa objaví workflow PR message exercise. Job Print PR message prebehne zeleno a krok Print message vypíše tvoju správu."], ["Šablónu neupravuj na pôvodnom mieste. Aktívne workflow musí byť v .github/workflows a YAML musí zachovať správne odsadenie. npm test odmietne ponechané zástupné hodnoty."], "Prečo filter branches pri udalosti pull_request sleduje cieľovú vetvu PR?")
    }, commands: [command("git switch -c participant/GITHUB_USER/actions-pr-message", "Vytvoří větev pro vlastní workflow.", "Vytvorí vetvu pre vlastné workflow."), command("cp workshop/templates/pr-message.yml .github/workflows/pr-message-GITHUB_USER.yml\nnotepad .github/workflows/pr-message-GITHUB_USER.yml", "Zkopíruje neaktivní šablonu mezi aktivní workflow a otevře ji.", "Skopíruje neaktívnu šablónu medzi aktívne workflow a otvorí ju."), command("npm test", "Ověří, že nezůstala žádná zástupná hodnota a ostatní testy procházejí.", "Overí, že nezostala žiadna zástupná hodnota a ostatné testy prechádzajú."), command("git add .github/workflows/pr-message-GITHUB_USER.yml\ngit commit -m \"ci: add pull request message\"\ngit push -u origin participant/GITHUB_USER/actions-pr-message", "Publikuje vlastní workflow do PR.", "Publikuje vlastné workflow do PR.")]
  },
  {
    id: "actions-failure", chapter: "actions", duration: 30,
    content: {
      cs: cs("Rozbij, přečti, oprav", "Červený check není verdikt. Je to stopa, kterou čteme od první konkrétní chyby.", ["CI log ukazuje výstup každého stepu. Při selhání se uloží Playwright report, screenshot a trace jako artifact. Artifact je soubor vzniklý během běhu, který si lze stáhnout i po skončení runneru."], ["V app.js dočasně přidej za filtrování receptů .slice(0, 1). Pushni rozbitou změnu, najdi první konkrétní chybu a stáhni artifact. Potom slice odstraň, spusť testy a pushni opravu."], ["První běh je červený a ukáže pouze jeden recept; opravený běh je zelený bez změkčení testu."], ["Neměň test jen proto, aby přestal hlásit skutečně rozbitou funkci. Řádek má zůstat const visibleRecipes = recipes.filter(recipe => recipe.locale === activeLocale);"], "Co ti log řekne dřív než screenshot a k čemu je artifact?"),
      sk: sk("Rozbi, prečítaj, oprav", "Červený check nie je verdikt. Je to stopa, ktorú čítame od prvej konkrétnej chyby.", ["CI log ukazuje výstup každého stepu. Pri zlyhaní sa uloží Playwright report, screenshot a trace ako artifact. Artifact je súbor vzniknutý počas behu, ktorý si možno stiahnuť aj po skončení runnera."], ["V app.js dočasne pridaj za filtrovanie receptov .slice(0, 1). Pushni pokazenú zmenu, nájdi prvú konkrétnu chybu a stiahni artifact. Potom slice odstráň, spusti testy a pushni opravu."], ["Prvý beh je červený a ukáže iba jeden recept; opravený beh je zelený bez zmäkčenia testu."], ["Nemeň test iba preto, aby prestal hlásiť skutočne pokazenú funkciu. Riadok má zostať const visibleRecipes = recipes.filter(recipe => recipe.locale === activeLocale);"], "Čo ti log povie skôr než screenshot a na čo slúži artifact?")
    }, commands: [command("const visibleRecipes = recipes.filter(recipe => recipe.locale === activeLocale).slice(0, 1);", "Dočasná rozbíjecí změna v app.js, není to příkaz terminálu.", "Dočasná poškodzujúca zmena v app.js, nie je to príkaz terminálu.", true), command("npm test\ngit add app.js\ngit commit -m \"fix: obnovit vsechny recepty\"\ngit push", "Po opravě vše ověří a publikuje.", "Po oprave všetko overí a publikuje.")]
  },
  {
    id: "actions-pr-rules", chapter: "actions", duration: 20,
    content: {
      cs: cs("Čitelné názvy a chráněný main", "Pravidla převádějí týmovou dohodu na automaticky ověřitelnou podmínku.", ["Conventional Commit začíná typem jako feat, fix, docs, test nebo ci. Kontrola názvu PR pomáhá orientaci. Ruleset může vyžadovat PR, review a zelené checks a zároveň blokovat přímý push do main."], ["Porovnej názvy uprava receptu a feat: add potion recipe. Potom na chráněném main ověř, že bez review nebo se selhaným checkem nejde PR sloučit."], ["Platný název i oba povinné checks jsou zelené a merge se zpřístupní až po review."], ["Admin bypass pravidla skryje smysl cvičení. Opravu posílej do stejné pracovní větve."], "Co chrání main před změnou, která nebyla zkontrolovaná člověkem ani testy?"),
      sk: sk("Čitateľné názvy a chránený main", "Pravidlá premieňajú tímovú dohodu na automaticky overiteľnú podmienku.", ["Conventional Commit začína typom ako feat, fix, docs, test alebo ci. Kontrola názvu PR pomáha orientácii. Ruleset môže vyžadovať PR, review a zelené checks a zároveň blokovať priamy push do main."], ["Porovnaj názvy uprava receptu a feat: add potion recipe. Potom na chránenom main over, že bez review alebo so zlyhaným checkom nemožno PR zlúčiť."], ["Platný názov aj oba povinné checks sú zelené a merge sa sprístupní až po review."], ["Admin bypass pravidla skryje zmysel cvičenia. Opravu posielaj do rovnakej pracovnej vetvy."], "Čo chráni main pred zmenou, ktorú neskontroloval človek ani testy?")
    }, commands: [command("feat: add potion recipe", "Platný název PR nebo commit zpráva.", "Platný názov PR alebo commit správa."), command("git push origin main", "Na chráněném main má být přímý push odmítnut.", "Na chránenom main má byť priamy push odmietnutý.", true)]
  },
  {
    id: "actions-release-pages", chapter: "actions", duration: 25,
    content: {
      cs: cs("Od merge k release a webu", "Po merge do main mohou navázat další automatické důsledky.", ["semantic-release čte Conventional Commits, vytvoří verzi, Git tag a GitHub Release. GITHUB_TOKEN je krátkodobé vestavěné oprávnění workflow; permissions mu mají dát jen nezbytný přístup. Pages workflow sestaví statický artifact a nasadí jej na veřejnou URL."], ["Slouč schválený PR volbou Create a merge commit. Sleduj CI, Release a Deploy Potion Archive. V release.yml najdi permissions a GITHUB_TOKEN, v pages.yml cestu k publikovanému artifactu."], ["Po merge jsou workflow zelená, případná verze má Git tag a web na Pages obsahuje novou změnu."], ["Secrets nepatří do YAML, souborů ani logů. docs, test nebo ci commit nemusí vytvořit novou produktovou verzi; feat vytvoří minor a fix patch."], "Jak se liší GitHub Release, Pages deployment a artifact jednoho CI běhu?"),
      sk: sk("Od merge k release a webu", "Po merge do main môžu nadviazať ďalšie automatické dôsledky.", ["semantic-release číta Conventional Commits, vytvorí verziu, Git tag a GitHub Release. GITHUB_TOKEN je krátkodobé vstavané oprávnenie workflow; permissions mu majú dať iba nevyhnutný prístup. Pages workflow zostaví statický artifact a nasadí ho na verejnú URL."], ["Zlúč schválený PR voľbou Create a merge commit. Sleduj CI, Release a Deploy Potion Archive. V release.yml nájdi permissions a GITHUB_TOKEN, v pages.yml cestu k publikovanému artifactu."], ["Po merge sú workflow zelené, prípadná verzia má Git tag a web na Pages obsahuje novú zmenu."], ["Secrets nepatria do YAML, súborov ani logov. docs, test alebo ci commit nemusí vytvoriť novú produktovú verziu; feat vytvorí minor a fix patch."], "Ako sa líši GitHub Release, Pages deployment a artifact jedného CI behu?")
    }, commands: [command("git log --oneline --graph --decorate --all -15", "Ukáže merge commit i případný release tag.", "Ukáže merge commit aj prípadný release tag.")]
  }
];

export const cheatSheet = [
  { id: "state", name: { cs: "Stav", sk: "Stav" }, items: [command("pwd", "Kde právě jsem.", "Kde práve som."), command("git status", "Co je změněné, staged a na jaké jsem větvi.", "Čo je zmenené, staged a na akej som vetve."), command("git status --short", "Zkrácený přehled stavu.", "Skrátený prehľad stavu."), command("git branch --show-current", "Název aktuální větve.", "Názov aktuálnej vetvy.") ] },
  { id: "changes", name: { cs: "Změny", sk: "Zmeny" }, items: [command("git diff", "Změny mimo staging.", "Zmeny mimo staging."), command("git diff --staged", "Změny připravené do commitu.", "Zmeny pripravené do commitu."), command("git add SOUBOR", "Vybere soubor do příštího commitu.", "Vyberie súbor do budúceho commitu.") ] },
  { id: "commit", name: { cs: "Commit", sk: "Commit" }, items: [command('git commit -m "feat: popis zmeny"', "Uloží staged změny do historie.", "Uloží staged zmeny do histórie."), command("git commit --amend --no-edit", "Doplní poslední lokální commit.", "Doplní posledný lokálny commit.") ] },
  { id: "history", name: { cs: "Historie", sk: "História" }, items: [command("git log --oneline --graph --decorate --all", "Graf větví a commitů.", "Graf vetiev a commitov."), command("git show HEAD", "Detail posledního commitu.", "Detail posledného commitu."), command("git blame SOUBOR", "Původ jednotlivých řádků.", "Pôvod jednotlivých riadkov.") ] },
  { id: "restore", name: { cs: "Vracení", sk: "Vracanie" }, items: [command("git restore SOUBOR", "Zahodí necommitnutou změnu.", "Zahodí necommitnutú zmenu."), command("git restore --staged SOUBOR", "Vyjme soubor ze staging area.", "Vyberie súbor zo staging area."), command("git revert HASH", "Přidá opačný commit.", "Pridá opačný commit.") ] },
  { id: "branches", name: { cs: "Větve", sk: "Vetvy" }, items: [command("git switch -c feature/nazev", "Vytvoří a otevře větev.", "Vytvorí a otvorí vetvu."), command("git switch main", "Přepne na main.", "Prepne na main."), command("git merge --no-ff feature/nazev", "Sloučí větev merge commitem.", "Zlúči vetvu merge commitom."), command("git branch -d feature/nazev", "Smaže sloučenou lokální větev.", "Zmaže zlúčenú lokálnu vetvu.") ] },
  { id: "conflict", name: { cs: "Konflikty", sk: "Konflikty" }, items: [command("git status", "Ukáže konfliktní soubory.", "Ukáže konfliktné súbory."), command("git add SOUBOR && git commit", "Potvrdí vyřešení a dokončí merge.", "Potvrdí vyriešenie a dokončí merge."), command("git merge --abort", "Zruší probíhající merge.", "Zruší prebiehajúce zlúčenie.") ] },
  { id: "remote", name: { cs: "Remote", sk: "Remote" }, items: [command("git remote -v", "Ukáže vzdálené adresy.", "Ukáže vzdialené adresy."), command("git fetch origin", "Stáhne vzdálenou historii.", "Stiahne vzdialenú históriu."), command("git pull", "Stáhne a začlení změny.", "Stiahne a začlení zmeny."), command("git push -u origin VETEV", "Publikuje větev a nastaví upstream.", "Publikuje vetvu a nastaví upstream."), command("git fetch --prune", "Odstraní staré remote-tracking ukazatele.", "Odstráni staré remote-tracking ukazovatele.") ] },
  { id: "tags", name: { cs: "Tagy", sk: "Tagy" }, items: [command('git tag -a v0.1.0 -m "Prvni verze"', "Označí konkrétní commit.", "Označí konkrétny commit."), command("git push origin v0.1.0", "Pošle tag na GitHub.", "Pošle tag na GitHub.") ] },
  { id: "danger", name: { cs: "Rizikové", sk: "Rizikové" }, items: [command("git reset --hard HEAD~1", "Zahodí commit i pracovní změny; jen v cvičném repu.", "Zahodí commit aj pracovné zmeny; iba v cvičnom repozitári.", true), command("git push --force", "Může přepsat sdílenou historii. Na workshopu nepoužívat.", "Môže prepísať zdieľanú históriu. Na workshope nepoužívať.", true) ] }
];
