name: Aktion-Fix-Everything
 

on:
  pull_request: 
    branches: [main]

permissions:
  contents: read

jobs:
  message:
    name: send-message
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "The Aktion fixed everything as have been said. :)"
